### ISSUE TITLE
Find this lib in SDK

### ISSUE THREAD

**Issue by patelakshay13890** [JulienGenoud/android-percent-support-lib-sample#1]
Where can I found this lib. in SDK to use in Eclipse??

**Comment by JulienGenoud** [comment]
you juste have to add this dependency to gradle:
com.android.support:percent:22.2.0

**Comment by patelakshay13890** [comment]
In Eclipse how can I use this ??

**Comment by JulienGenoud** [comment]
try to follow this steps :
https://developer.android.com/tools/support-library/setup.html#libs-with-res

**Comment by patelakshay13890** [comment]
Yes, but in SDK where I can found this ??
I have Support Design Lib. imported in Eclipse

**Comment by JulienGenoud** [comment]
I don't really know how to do ...
maybe it's time to migrate to android studio ?
http://android-developers.blogspot.fr/2015/06/an-update-on-eclipse-android-developer.html

**Comment by yelinaung** [comment]
Yup. It's the time to ditch Eclipse and move on to Android Studio already.

I'm not very sure this is the correct path but I've found the `percent-22.2.0.aar` under this location 

`ANDROID_SDK_PATH/extras/android/m2repository/com/android/support/percent/22.2.0/`

And the contents. 

``` bash
λ ~:android-sdk ls -la extras/android/m2repository/com/android/support/percent/22.2.0/
total 72
drwxr-xr-x  8 yelinaung  staff    272 May 29 11:50 .
drwxr-xr-x  7 yelinaung  staff    238 Jun 29 12:21 ..
-rw-r--r--  1 yelinaung  staff  12466 May 29 11:50 percent-22.2.0.aar
-rw-r--r--  1 yelinaung  staff     32 May 29 11:50 percent-22.2.0.aar.md5
-rw-r--r--  1 yelinaung  staff     40 May 29 11:50 percent-22.2.0.aar.sha1
-rw-r--r--  1 yelinaung  staff    670 May 29 11:50 percent-22.2.0.pom
-rw-r--r--  1 yelinaung  staff     32 May 29 11:50 percent-22.2.0.pom.md5
-rw-r--r--  1 yelinaung  staff     40 May 29 11:50 percent-22.2.0.pom.sha1
```
