### ISSUE TITLE
How to set width to element in layout programaticaly?

### ISSUE THREAD

**Issue by zachross90210** [JulienGenoud/android-percent-support-lib-sample#10]
Hello, please tell me how to set it . I create layout in xml, now i want add elements to this layout programaticaly. But elements not have params like widthPercent.
how to?

**Comment by jjhesk** [comment]
+1

**Comment by JulienGenoud** [comment]
You can try something like this.

View view = findViewById(...);
PercentRelativeLayout.LayoutParams params = 
(PercentRelativeLayout.LayoutParams) view.getLayoutParams();
PercentLayoutHelper.PercentLayoutInfo info = params.getPercentLayoutInfo();
info.widthPercent  = 0.10;
view.requestLayout();

**Comment by andersonb** [comment]
@JulienGenoud I got a cast exception :(

java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.support.percent.PercentRelativeLayout$LayoutParams

**Comment by trghauri** [comment]
not working this solution...

 View view = findViewById(R.id.bar1);
                 PercentLayoutHelper.PercentLayoutParams params =(PercentLayoutHelper.PercentLayoutParams) view.getLayoutParams();
                 PercentLayoutHelper.PercentLayoutInfo info = params.getPercentLayoutInfo();
                 info.widthPercent = (float) 0.20;
                 view.requestLayout();
