### ISSUE TITLE
Error when run project

### ISSUE THREAD

**Issue by Harin-Kaklotar** [JulienGenoud/android-percent-support-lib-sample#11]
it sync properly but
When i run project, it give me error
Error:Execution failed for task ':DemoNewNFC:dexDebug'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_79\bin\java.exe'' finished with non-zero exit value 2

and application not start because of this error

**Comment by JulienGenoud** [comment]
Hi are you sur to compile the right project the prefix is "app"  and not "DemoNewNFC" .

**Comment by Harin-Kaklotar** [comment]
yes

**Comment by JulienGenoud** [comment]
ok can you give the full verbose gradle log
